#!/bin/bash

#set -x

E_BADARGS=65

EXPECTED_ARGS=3

if [ $# -ne $EXPECTED_ARGS ]
then
  echo " This script expect $EXPECTED_ARGS arguments instead of $#"
  exit $E_BADARGS
fi

MV=$(which mv)
RM=$(which rm)
DATE=$(which date)
SED=$(which sed)
CAT=$(which cat)
DRUSH=$(which drush)


### CONFIG
DEP_NAME=$1
DEP_BRANCH=$2
DEP_USER=$3

. $($(which dirname) $($(which readlink) -f "$0"))/autodeploy-common.sh

# Clonar RAMA REPO con submoduless en dir tmp
# clone-with-subs.sh $REPO $BRANCH $TARGET
. $LIB/clone-with-subs.sh $REPO_BARE $DEP_BRANCH $TMP_DIR $TAG

# Copiar files y settings
# copy-files-settings.sh $SOURCE $TARGET
. $LIB/drupal-copy-files-settings.sh $DST_DIR${BOLIERPLATE_DIR} $TMP_DIR${BOLIERPLATE_DIR}

# Arreglar permisos
# fix-drupal-perms.sh $TARGET
. $LIB/drupal-fix-perms.sh $TMP_DIR${BOLIERPLATE_DIR}

# Firmar Robots
REPO_HASH=$($CAT $TMP_DIR/.git_hash)
REPO_DATE=$($CAT $TMP_DIR/.git_date)
SIGN="# Environment generated by $DEP_USER from $DEP_BRANCH (hash: $REPO_HASH, date: $REPO_DATE) for site $SITE_NAME on $($DATE '+%Y-%m-%d %H:%M %Z')"
$SED  -i  '1{s|^|'"${SIGN}\n"'|}' $TMP_DIR${BOLIERPLATE_DIR}/robots.txt

# Eliminar archivos no para produccion
$RM $TMP_DIR/.git*

# Loggear despliegue
LOG_DIR=$($(which dirname) "${LOG_FILE}")
if [ ! -d $LOG_DIR ]; then
  mkdir -p $LOG_DIR
fi
echo -e "$($DATE '+%Y-%m-%d %H:%M %Z')\t$DEP_BRANCH\t$REPO_DATE\t$REPO_HASH\t$DEP_USER" >> $LOG_FILE

$RM -r $DST_DIR${BOLIERPLATE_DIR}
$MV $TMP_DIR${BOLIERPLATE_DIR} $DST_DIR${BOLIERPLATE_DIR}

# Reload apache
restartServerIfNecesary

# Borrar caches
COLUMNS=72 $DRUSH -r $DST_DIR${BOLIERPLATE_DIR} -l $SITE_NAME cc all

# Clean Varnish
cleanVarnishIfNecesary

exit 0
